### ISSUE TITLE
Revision TODO

### ISSUE THREAD

**Issue by johirbuet** [johirbuet/BoatRevision#1]
TODO List:
 Reviewer #2
- [x] The domain types provided in Figure 3 are very limited to specific transportation data analytics problems. Each model of transportation includes very different types of data and data sources. It is expected by the authors to explain how BoaT could be extended to a wider range of transportation data-related problems (e.g maintenance-related data, scheduling-related data, etc). Although this has been mentioned in Section 5.1, measuring the applicability of BoaT on a wide range of transportation-related data is not still clarified.
- [x] Moreover, there are some editing issues in statements such as the examples provide as follow which necessitates the careful revision of the article by the authors:
    Page 1, line 48, "using a distributed cluster with an adequate number of nodes problems related to……"
 Page 2, line 7, "the work describes a transportation-specific Big Data …. and its infrastructure that is aims at…"
- [x] Page 4, line 8, "whereas BoaT built on top of Boa is provides the support of…"
- [x] The authors are recommended to provide keywords after the abstract.
- [x] Coming to the Bibliography some references such as reference 10, includes unnecessary information which should be removed and become consistent accordingly.

Reviewer #4
- [x] My only minor comment is for the authors to give the paper a good proof-read, and fix any identified types.  I have caught a number of those while reading the paper.  A few examples are:
 a. The second paragraph on page 2 shows some repetition of sentences.
 b. Missing period - first paragraph of section 2 (Motivation) - the sentence …The query becomes hard to solve in Matlab or even R and could potentially run for a long time in Java (period missing here) Answering this question in Java would require knowledge of (at a minimum):
